name: smart_labs_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.2.2
  provider: ^6.1.2
  fl_chart: ^0.65.0
  flutter_dotenv: ^5.2.1
  jwt_decoder: ^2.0.1
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  logger: ^2.5.0
  flutter_multi_select_items: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
