name: smart_labs_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.2.2
  provider: ^6.1.2
  fl_chart: ^0.65.0
  flutter_dotenv: ^5.2.1
  jwt_decoder: ^2.0.1
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  logger: ^2.5.0
  flutter_multi_select_items: ^0.4.3
  timeago: ^3.7.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  device_info_plus: ^11.3.0
  file_picker: ^8.3.5
  awesome_snackbar_content: ^0.1.5
  collection: ^1.19.0
  flutter_keyboard_visibility: ^6.0.0
  http_parser: ^4.1.2
  url_launcher: ^6.3.1
  open_filex: ^4.6.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
